import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {  
  // Existing translations
  'message': 'What is your name',
  'name': 'Muhammad Idrees',
  'showd': 'GetX Dialog Alert',
  'title': 'Face Features Analysis',
  'apply': 'Apply',
  'english': 'English',
  'urdu': 'Urdu',
  'afrikaans': 'Afrikaans',
  'select_language': 'Select Language',
  'dialog_title': 'Delete Chat',
  'dialog_message': 'Are you sure you want to delete the chat?',
  'app_name': 'RePixel',
  'go_pro': 'Go Pro',
  'streak': 'Streak',
  'streak_count': 'X3',
  'now_check_features': 'Now check Your Facial Features',
  'score_and_rating': 'Score and Rating',
  'most_used': 'Most Used',
  'improve_clarity': 'Improve Clarity',
  'make_photos_pop': 'Make Photos pop by greying',
  'out_background': 'Out Background',
  'de_scratch': 'De-Scratch',
  'popular_features': 'Popular Features',
  'enhance': 'Enhance',
  'menu': 'Menu',
  'share': 'Share',
  'share_text': 'Share Text',
  'feedback': 'Feed Back',
  'rating_box': 'Rating Box', // Fixed typo from "Ratting" to "Rating"
  'check_play_store': 'Check Out Play Store',
  'tab_bar': 'Tab Bar',
  'get_app_info': 'Get App Info',
  'languages': 'Languages',
},
   'af': {  
  // Existing translations
  'message': 'Wat is jou naam?',
  'name': 'Muhammad Idrees',
  'showd': 'GetX Dialoog Alarm',
  'title': 'Gesigskenmerke Analise',
  'apply': 'Pas toe',
  'english': 'Engels',
  'urdu': 'Oerdoe',
  'afrikaans': 'Afrikaans',
  'select_language': 'Kies Taal',
  'dialog_title': 'Verwyder Gesprek',
  'dialog_message': 'Is jy seker jy wil die gesprek verwyder?',
  
  // New HomeScreen translations
  'app_name': 'RePixel',
  'go_pro': 'Gaan Pro',
  'streak': 'Reeks',
  'streak_count': 'X3',
  'now_check_features': 'Kontroleer nou jou gesigskenmerke',
  'score_and_rating': 'Punt en Gradering',
  'most_used': 'Meeste Gebruik',
  'improve_clarity': 'Verbeter Duidelikheid',
  'make_photos_pop': 'Maak foto\'s opvallend',
  'out_background': 'Agtergrond Uit',
  'de_scratch': 'Verwyder Krapmerke',
  'popular_features': 'Gewilde Kenmerke',
  'enhance': 'Verbeter',
  'menu': 'Kieslys',
  'share': 'Deel',
  'share_text': 'Deel Teks',
  'feedback': 'Terugvoer',
  'rating_box': 'Graderingsboks',
  'check_play_store': 'Besoek Play Store',
  'tab_bar': 'Oortjie Balk',
  'get_app_info': 'Kry App Inligting',
  'languages': 'Tale',
},
'ar': {
  'message': 'ما اسمك؟',
  'name': 'محمد إدريس',
  'showd': 'تنبيه حوار GetX',
  'title': 'تحليل ملامح الوجه',
  'apply': 'تطبيق',
  'english': 'الإنجليزية',
  'urdu': 'الأردية',
  'afrikaans': 'الأفريكانية',
  'select_language': 'اختر اللغة',
  'dialog_title': 'حذف المحادثة',
  'dialog_message': 'هل أنت متأكد أنك تريد حذف المحادثة؟',
  'app_name': 'ري بيكسل',
  'go_pro': 'الترقية إلى برو',
  'streak': 'سلسلة',
  'streak_count': '×3',
  'now_check_features': 'تحقق الآن من ملامح وجهك',
  'score_and_rating': 'الدرجة والتقييم',
  'most_used': 'الأكثر استخدامًا',
  'improve_clarity': 'تحسين الوضوح',
  'make_photos_pop': 'اجعل الصور تبرز عن طريق تعتيم',
  'out_background': 'الخلفية',
  'de_scratch': 'إزالة الخدوش',
  'popular_features': 'الميزات الشائعة',
  'enhance': 'تحسين',
  'menu': 'القائمة',
  'share': 'مشاركة',
  'share_text': 'مشاركة النص',
  'feedback': 'ملاحظات',
  'rating_box': 'مربع التقييم',
  'check_play_store': 'تفقد متجر Play',
  'tab_bar': 'شريط التبويبات',
  'get_app_info': 'معلومات التطبيق',
  'languages': 'اللغات',
},
'zh': {
  'message': '你叫什么名字？',
  'name': '穆罕默德·伊德里斯',
  'showd': 'GetX 弹窗提示',
  'title': '面部特征分析',
  'apply': '应用',
  'english': '英语',
  'urdu': '乌尔都语',
  'afrikaans': '南非荷兰语',
  'select_language': '选择语言',
  'dialog_title': '删除聊天',
  'dialog_message': '你确定要删除此聊天吗？',
  'app_name': 'RePixel',
  'go_pro': '升级专业版',
  'streak': '连续记录',
  'streak_count': 'X3',
  'now_check_features': '现在检查你的面部特征',
  'score_and_rating': '评分与评价',
  'most_used': '最常用',
  'improve_clarity': '提高清晰度',
  'make_photos_pop': '通过灰化使照片更突出',
  'out_background': '去除背景',
  'de_scratch': '去划痕',
  'popular_features': '热门功能',
  'enhance': '增强',
  'menu': '菜单',
  'share': '分享',
  'share_text': '分享文本',
  'feedback': '反馈',
  'rating_box': '评分框',
  'check_play_store': '查看 Play 商店',
  'tab_bar': '标签栏',
  'get_app_info': '获取应用信息',
  'languages': '语言',
},
'zh_Hant': {
  'message': '你叫什麼名字？',
  'name': '穆罕默德·伊德里斯',
  'showd': 'GetX 對話提示',
  'title': '面部特徵分析',
  'apply': '套用',
  'english': '英語',
  'urdu': '烏爾都語',
  'afrikaans': '南非語',
  'select_language': '選擇語言',
  'dialog_title': '刪除聊天',
  'dialog_message': '你確定要刪除此聊天嗎？',
  'app_name': 'RePixel',
  'go_pro': '升級專業版',
  'streak': '連續次數',
  'streak_count': 'X3',
  'now_check_features': '立即查看您的面部特徵',
  'score_and_rating': '分數與評分',
  'most_used': '最常使用',
  'improve_clarity': '提高清晰度',
  'make_photos_pop': '透過灰化讓照片更出色',
  'out_background': '移除背景',
  'de_scratch': '去刮痕',
  'popular_features': '熱門功能',
  'enhance': '增強',
  'menu': '選單',
  'share': '分享',
  'share_text': '分享文字',
  'feedback': '回饋',
  'rating_box': '評分方塊',
  'check_play_store': '查看 Play 商店',
  'tab_bar': '分頁欄',
  'get_app_info': '取得應用程式資訊',
  'languages': '語言',
},
'cs': {
  'message': 'Jak se jmenuješ?',
  'name': 'Muhammad Idrees',
  'showd': 'Upozornění GetX dialog',
  'title': 'Analýza rysů obličeje',
  'apply': 'Použít',
  'english': 'Angličtina',
  'urdu': 'Urdu',
  'afrikaans': 'Afrikánština',
  'select_language': 'Vyberte jazyk',
  'dialog_title': 'Smazat konverzaci',
  'dialog_message': 'Opravdu chcete smazat tuto konverzaci?',
  'app_name': 'RePixel',
  'go_pro': 'Přejít na Pro',
  'streak': 'Šňůra',
  'streak_count': 'X3',
  'now_check_features': 'Nyní zkontrolujte své rysy obličeje',
  'score_and_rating': 'Skóre a hodnocení',
  'most_used': 'Nejčastěji používané',
  'improve_clarity': 'Zlepšit jasnost',
  'make_photos_pop': 'Zvýrazněte fotky pomocí šedého pozadí',
  'out_background': 'Odstranit pozadí',
  'de_scratch': 'Odstranit škrábance',
  'popular_features': 'Populární funkce',
  'enhance': 'Vylepšit',
  'menu': 'Nabídka',
  'share': 'Sdílet',
  'share_text': 'Sdílet text',
  'feedback': 'Zpětná vazba',
  'rating_box': 'Hodnoticí pole',
  'check_play_store': 'Zkontrolujte v obchodě Play',
  'tab_bar': 'Lišta záložek',
  'get_app_info': 'Získat informace o aplikaci',
  'languages': 'Jazyky',
},
'da': {
  'message': 'Hvad hedder du?',
  'name': 'Muhammad Idrees',
  'showd': 'GetX Dialog Advarsel',
  'title': 'Analyse af ansigtstræk',
  'apply': 'Anvend',
  'english': 'Engelsk',
  'urdu': 'Urdu',
  'afrikaans': 'Afrikaans',
  'select_language': 'Vælg sprog',
  'dialog_title': 'Slet samtale',
  'dialog_message': 'Er du sikker på, at du vil slette samtalen?',
  'app_name': 'RePixel',
  'go_pro': 'Opgrader til Pro',
  'streak': 'Stime',
  'streak_count': 'X3',
  'now_check_features': 'Tjek dine ansigtstræk nu',
  'score_and_rating': 'Point og vurdering',
  'most_used': 'Mest brugt',
  'improve_clarity': 'Forbedr klarhed',
  'make_photos_pop': 'Få billeder til at skille sig ud med gråtoneeffekt',
  'out_background': 'Fjern baggrund',
  'de_scratch': 'Fjern ridser',
  'popular_features': 'Populære funktioner',
  'enhance': 'Forbedr',
  'menu': 'Menu',
  'share': 'Del',
  'share_text': 'Del tekst',
  'feedback': 'Feedback',
  'rating_box': 'Vurderingsboks',
  'check_play_store': 'Tjek Play Butik',
  'tab_bar': 'Fanebjælke',
  'get_app_info': 'Hent app-information',
  'languages': 'Sprog',
},
'nl': {
  'message': 'Wat is je naam?',
  'name': 'Muhammad Idrees',
  'showd': 'GetX Dialoogwaarschuwing',
  'title': 'Analyse van Gezichtskenmerken',
  'apply': 'Toepassen',
  'english': 'Engels',
  'urdu': 'Urdu',
  'afrikaans': 'Afrikaans',
  'select_language': 'Selecteer taal',
  'dialog_title': 'Chat Verwijderen',
  'dialog_message': 'Weet je zeker dat je de chat wilt verwijderen?',
  'app_name': 'RePixel',
  'go_pro': 'Ga Pro',
  'streak': 'Reeks',
  'streak_count': 'X3',
  'now_check_features': 'Controleer nu je gezichtskenmerken',
  'score_and_rating': 'Score en Beoordeling',
  'most_used': 'Meest Gebruikt',
  'improve_clarity': 'Verbeter Helderheid',
  'make_photos_pop': 'Laat foto\'s opvallen met grijsfilter',
  'out_background': 'Achtergrond Verwijderen',
  'de_scratch': 'Krassen Verwijderen',
  'popular_features': 'Populaire Functies',
  'enhance': 'Verbeteren',
  'menu': 'Menu',
  'share': 'Delen',
  'share_text': 'Tekst Delen',
  'feedback': 'Feedback',
  'rating_box': 'Beoordelingsvak',
  'check_play_store': 'Bekijk in Play Store',
  'tab_bar': 'Tabbladbalk',
  'get_app_info': 'App-info Ophalen',
  'languages': 'Talen',
},
'fi': {
  'message': 'Mikä on nimesi?',
  'name': 'Muhammad Idrees',
  'showd': 'GetX-dialogihälytys',
  'title': 'Kasvonpiirteiden analyysi',
  'apply': 'Käytä',
  'english': 'Englanti',
  'urdu': 'Urdu',
  'afrikaans': 'Afrikaans',
  'select_language': 'Valitse kieli',
  'dialog_title': 'Poista keskustelu',
  'dialog_message': 'Haluatko varmasti poistaa keskustelun?',
  'app_name': 'RePixel',
  'go_pro': 'Siirry Pro-versioon',
  'streak': 'Putki',
  'streak_count': 'X3',
  'now_check_features': 'Tarkista nyt kasvonpiirteesi',
  'score_and_rating': 'Pisteet ja arviointi',
  'most_used': 'Eniten käytetty',
  'improve_clarity': 'Paranna selkeyttä',
  'make_photos_pop': 'Tuo kuvat esiin harmaasävytetysti',
  'out_background': 'Poista tausta',
  'de_scratch': 'Poista naarmut',
  'popular_features': 'Suositut ominaisuudet',
  'enhance': 'Paranna',
  'menu': 'Valikko',
  'share': 'Jaa',
  'share_text': 'Jaa teksti',
  'feedback': 'Palaute',
  'rating_box': 'Arviointikenttä',
  'check_play_store': 'Tarkista Play Kaupasta',
  'tab_bar': 'Välilehtipalkki',
  'get_app_info': 'Hae sovellustiedot',
  'languages': 'Kielet',
},
'fr': {
  'message': 'Quel est votre nom ?',
  'name': 'Muhammad Idrees',
  'showd': 'Alerte de dialogue GetX',
  'title': 'Analyse des caractéristiques du visage',
  'apply': 'Appliquer',
  'english': 'Anglais',
  'urdu': 'Ourdou',
  'afrikaans': 'Afrikaans',
  'select_language': 'Choisir la langue',
  'dialog_title': 'Supprimer la conversation',
  'dialog_message': 'Êtes-vous sûr de vouloir supprimer la conversation ?',
  'app_name': 'RePixel',
  'go_pro': 'Passer à Pro',
  'streak': 'Série',
  'streak_count': 'X3',
  'now_check_features': 'Vérifiez maintenant vos caractéristiques faciales',
  'score_and_rating': 'Score et évaluation',
  'most_used': 'Les plus utilisés',
  'improve_clarity': 'Améliorer la clarté',
  'make_photos_pop': 'Faites ressortir les photos avec du gris',
  'out_background': 'Supprimer l’arrière-plan',
  'de_scratch': 'Supprimer les rayures',
  'popular_features': 'Fonctionnalités populaires',
  'enhance': 'Améliorer',
  'menu': 'Menu',
  'share': 'Partager',
  'share_text': 'Partager le texte',
  'feedback': 'Retour d’information',
  'rating_box': 'Boîte d’évaluation',
  'check_play_store': 'Voir sur le Play Store',
  'tab_bar': 'Barre d’onglets',
  'get_app_info': 'Obtenir des informations sur l’application',
  'languages': 'Langues',
},
};
}